### ISSUE TITLE
Error during training: "error in running finalizer: Base.KeyError(key=32768)"

### ISSUE THREAD

**Issue by TugbaP** [ai-ku/Morse.jl#3]
I got this error while I was trying to replicate your Table 5 scores on trmorph2006 dataset.
![morphNetError](https://user-images.githubusercontent.com/5729763/62288216-94f00d00-b464-11e9-981b-bf3ce3fbe915.png)

As the first step, I only want to see the code is working on my computer. Therefore I started the training  with only 2 sentence; however it doesn't complete for a long time.
Could you help me about this error ?

**Comment by ekinakyurek** [comment]
This error (it is a warning) happens when a pretrained model exist in checkpoints/ folder. The code loads the existing model to gpu and there you get the warning.

However, if you are training 1 epoch on 2 sentence, you shouldn’t wait more than 10 min.

How did you set 2 sentence limit?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by TugbaP** [comment]
I directly changed trmor2006.train and .test files temporarily.
For now, training started; however I got another error in train.jl, line-175 where  _evaluation_ function is called.
![evalError_morphNetError](https://user-images.githubusercontent.com/5729763/62293363-1d74aa80-b471-11e9-9e4d-87ad1e31451d.png)

However, evaluate function exists in util.jl and is exported in Morse.jl file.

**Comment by ekinakyurek** [comment]
Are you sure that you keep the format of training and test files. It seemed to me that your [data](https://github.com/ai-ku/Morse.jl/blob/d31eb0e0c5b1057bdb0dfa073844515e4986049b/src/parser.jl#L280) array is empty due to a parsing issue.

________________________________

**Comment by ekinakyurek** [comment]
I realize that your problem might be related with using too small number of test sentences. The code tries to split a development set from the training set. We decided to use %10 as development set if an external development set isn't provided. So, you need to use at least 10 sentences for training set. I also recommend using ~1000 sentence for reliable training simulation.
